import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header>
          <div className="navbar bg-amber-50 shadow-sm">
            <div className="flex-1">
              <Link className="btn btn-primary text-xl" href="/">Tatil Mi?</Link>
            </div>
            <div className="flex gap-2">
              <input
                type="text"
                placeholder="Search"
                className="input bg-amber-100 w-24 md:w-auto"
              />
            </div>
          </div>
        </header>
        {children}
        <footer className="flex items-center justify-center footer footer-center mt-auto p-5 text-md sm:text-lg md:text-2xl border-t">
          footer
        </footer>
      </body>
    </html>
  );
}
