import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header>
          <nav className="navbar bg-amber-50 shadow-sm">
            <Link className="btn btn-primary text-xl" href="/">
              <i className="fa-regular fa-snowflake"></i>
              Tatil Mi?
            </Link>
          </nav>
        </header>
        {children}
        <footer className="flex items-center justify-center footer footer-center mt-auto p-5 text-md sm:text-lg md:text-2xl border-t">
          footer
        </footer>
      </body>
    </html>
  );
}
